Update codeql.yml

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -25,16 +25,22 @@ jobs:
           python --version
 
           # Install TruffleHog
-          #pip install truffleHog3
-          #pip install truffleHog3 --verbose
-          pip install  --upgrade truffleHog3
+          pip install --upgrade truffleHog3
 
       - name: Run TruffleHog Scan for Secrets
         run: |
-          # Scan the repository for secrets like API keys, passwords, tokens, etc.
-          trufflehog3 ./ || Write-Host "Secrets detected, but continuing workflow."
-          exit 0
-         
+          # Run TruffleHog and output the results in SARIF format
+          trufflehog3 --json --report-format=sarif --report-path=trufflehog_output.sarif . || Write-Host "Secrets detected, but continuing workflow."
+
+      - name: Check for TruffleHog SARIF File
+        run: |
+          # Ensure the SARIF file is generated
+          if (Test-Path "trufflehog_output.sarif") {
+            echo "✅ SARIF report generated successfully."
+          } else {
+            echo "❌ SARIF report NOT found!"
+            exit 1
+          }
 
       - name: Upload SARIF file to GitHub Code Scanning Alerts
         uses: github/codeql-action/upload-sarif@v3
@@ -42,4 +48,3 @@ jobs:
           sarif_file: trufflehog_output.sarif
           token: ${{ secrets.GITHUB_TOKEN }}
           wait-for-processing: true
-     
